### ISSUE TITLE
Please upgrade zendframework to laminas

### ISSUE THREAD

**Issue by Erseni** [researchgate/injektor#17]
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.

**Comment by danez** [comment]
Thanks for reporting, we will do this soon.

**Comment by danez** [comment]
Closed by https://github.com/researchgate/injektor/commit/b3a0e7f92e15db7a3b59d69afd909e9f9f18bacb, released in 2.0.0

Sorry for the delay.
