### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by Erseni** [researchgate/injektor#18]
Is PHP 8.0 supported with the new Attribute Syntax?

**Comment by mdio** [comment]
Hi and sorry for the late reply.
PHP 8.0 is currently not supported.
There are no short-term plans to support PHP 8.0 but I would expect us to work on it around Q2 2022.
Then we will also tackle issues like the one you mentioned in #19.

First we also need to upgrade to composer 2, which is blocked the current version of `ocramius/proxy-manager` which has a sub-dependency that binds to the `composer-plugin-api` 1.x.
