### ISSUE TITLE
PHP 8.0 Deprecation Warning

### ISSUE THREAD

**Issue by Erseni** [researchgate/injektor#19]
The DependencyInjectionContainer uses ReflectionParameter::getClass() which is deprecated since php 8.0

```
Deprecated: Method ReflectionParameter::getClass() is deprecated in vendor/rg/injektor/src/rg/injektor/DependencyInjectionContainer.php on line 817
```

**Comment by mdio** [comment]
Thank you for bringing this up!
As mentioned in the other issue, there are no short-term plans to support PHP 8.0.
